force-app/main/default/objects/Attendee__c/Attendee__c.object-meta.xml
<CustomObject>
    <label>Attendee</label>
    <nameField>
        <label>Attendee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Attendees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <label>Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Attendee__c/Event_Attendee__c.object-meta.xml
<CustomObject>
    <label>Event Attendee</label>
    <nameField>
        <label>Event Attendee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event Attendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Organizer__c/Event_Organizer__c.object-meta.xml
<CustomObject>
    <label>Event Organizer</label>
    <nameField>
        <label>Event Organizer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event Organizers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Location__c/Location__c.object-meta.xml
<CustomObject>
    <description>This object is to capture the location details</description>
    <label>Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Location__c/fields/Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>Postal_Code__c</fullName>
    <description>This field is to capture the postal code of given location</description>
    <inlineHelpText>Location Postal Code</inlineHelpText>
    <label>Postal Code</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Location__c/fields/Street__c.field-meta.xml
<CustomField>
    <fullName>Street__c</fullName>
    <description>This field is to capture the street of location</description>
    <inlineHelpText>Enter Street Details</inlineHelpText>
    <label>Street</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/EventAttendeeHelper.cls
/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 10-11-2020
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
 * Modifications Log 
 * Ver   Date         Author                               Modification
 * 1.0   10-11-2020   ChangeMeIn@UserSettingsUnder.SFDoc   Initial Version
**/
public with sharing class EventAttendeeHelper {
    public
    static void sendConfirmationEmail(List<Event_Attendee__c> newRecordList,Map<Id,Event_Attendee__c> newRecordMap){
        Set<Id> attendeesIdSet = new Set<Id>();
        Set<Id> eventIdSet = new Set<Id>();
        Map<Id,Attendee__c> attendeesMap = new Map<Id,Attendee__c>();
        Map<Id,Event__c> eventMap = new Map<Id,Event__c>();
        Attendee__c attendeeRecord = new Attendee__c();
        Event__c eventRecord = new Event__c();
        String emailBody = System.Label.Email_Content;
        Messaging.SingleEmailMessage message = new Messaging.SingleEmailMessage();

        for(Event_Attendee__c newRecord : newRecordList){
            attendeesIdSet.add(newRecord.Attendee__c);
            eventIdSet.add(newRecord.Event__c);
        }

        attendeesMap = getAttendeeMap(attendeesIdSet);
        eventMap = getEventMap(eventIdSet);

        for(Event_Attendee__c eventAttendeeRecord : newRecordList){
            attendeeRecord = attendeesMap.get(eventAttendeeRecord.Attendee__c);
            eventRecord = eventMap.get(eventAttendeeRecord.Event__c);
            message.setToAddresses(new List<String>{attendeeRecord.Email__c});
            message.optOutPolicy = 'FILTER';
            message.setSubject('Pass for the '+eventRecord.Name);
            message.setSenderDisplayName(eventRecord.Event_Organizer__r.Name);
            emailBody.replace('{AttendeeName}',attendeeRecord.Name);
            emailBody.replace('{EventName}',eventRecord.Name);
            emailBody.replace('{EventDate}', String.valueOf(eventRecord.Start_Date_Time__c));
            emailBody.replace('{EventLocation}',eventRecord.Location__r.Name);
            emailBody.replace('{EventLocation}',eventRecord.Location__r.Name);
            emailBody.replace('{Location}',eventRecord.Location__r.Postal_Code__c);
            emailBody.replace('{OrganizerName}',eventRecord.Event_Organizer__r.Name);
        }
    }
    private
    static Map<Id,Attendee__c> getAttendeeMap(Set<Id> attendeesIdSet){
        return new Map<Id,Attendee__c>([
            SELECT
                Id,
                Name,
                Email__c
            FROM
                Attendee__c
            WHERE
                ID IN :attendeesIdSet
        ]);
    }
    private
    static Map<Id,Event__c> getEventMap(Set<Id> eventIdSet){
        return new Map<Id,Event__c>([
            SELECT
                Id,
                Name,
                Start_Date_Time__c,
                Event_Organizer__c,
                Event_Organizer__r.Name,
                Location__c,
                Location__r.Name,
                Location__r.City__c,
                Location__r.Country__c,
                Location__r.State__c,
                Location__r.Street__c,
                Location__r.Postal_Code__c
            FROM
                Event__c
            WHERE
                ID IN :eventIdSet
        ]);
    }
    
}