force-app/main/default/objects/Attendee__c/Attendee__c.object-meta.xml
<CustomObject>
    <label>Attendee</label>
    <nameField>
        <label>Attendee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Attendees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <label>Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Attendee__c/Event_Attendee__c.object-meta.xml
<CustomObject>
    <label>Event Attendee</label>
    <nameField>
        <label>Event Attendee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event Attendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Speaker__c/Event_Speaker__c.object-meta.xml
<CustomObject>
    <label>Event Speaker</label>
    <nameField>
        <label>Event Speaker Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event Speakers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Location__c/Location__c.object-meta.xml
<CustomObject>
    <description>This object is to capture the location details</description>
    <label>Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Location__c/fields/Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>Postal_Code__c</fullName>
    <description>This field is to capture the postal code of given location</description>
    <inlineHelpText>Location Postal Code</inlineHelpText>
    <label>Postal Code</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Location__c/fields/Street__c.field-meta.xml
<CustomField>
    <fullName>Street__c</fullName>
    <description>This field is to capture the street of location</description>
    <inlineHelpText>Enter Street Details</inlineHelpText>
    <label>Street</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Speaker__c/Speaker__c.object-meta.xml
<CustomObject>
    <label>Speaker</label>
    <nameField>
        <label>Speaker Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Speakers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/EventDetailsController.cls
/**
 * @description       : 
 * @author            : gaur.puneet@outlook.com
 * @group             : 
 * @last modified on  : 11-29-2020
 * @last modified by  : gaur.puneet@outlook.com
 * Modifications Log 
 * Ver   Date         Author                    Modification
 * 1.0   11-12-2020   gaur.puneet@outlook.com   Initial Version
**/
public with sharing class EventDetailsController {
    @AuraEnabled
    public static List<Event_Speaker__c> getSpeakers(String eventId){
        List<Event_Speaker__c> speakerList = [
            SELECT
                Id,
                Name,
                Speaker__c,
                Speaker__r.Name,
                Speaker__r.Phone__c,
                Speaker__r.Email__c,
                Speaker__r.Company__c
            FROM
                Event_Speaker__c
            WHERE
                Event__c = :eventId
            WITH SECURITY_ENFORCED
        ];
        return speakerList;
    }
    @AuraEnabled
    public static Event__c getLocationDetails(String eventId){
        try {
            Event__c eventRecord = [
                SELECT
                    Id,
                    Name,
                    Location__c,
                    Location__r.Name,
                    Location__r.City__c,
                    Location__r.Country__c, 
                    Location__r.Land_Mark__c, 
                    Location__r.Postal_Code__c, 
                    Location__r.State__c,
                    Location__r.Street__c
                FROM
                    Event__c
                WHERE
                    Id = :eventId
                WITH SECURITY_ENFORCED
            ];
            return eventRecord;
            
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
    @AuraEnabled
    public static List<Event_Attendee__c> getEventAttendee(String eventId){
        List<Event_Attendee__c> eventAttendeesList = new List<Event_Attendee__c>();
        try {
            eventAttendeesList = [
                SELECT
                    ID,
                    Name, 
                    Attendee__c,
                    Attendee__r.Name,
                    Attendee__r.Company_Name__c,
                    Attendee__r.Email__c, 
                    Attendee__r.Location__r.Name,
                    Attendee__r.Location__c
                FROM
                    Event_Attendee__c
                WHERE
                    Event__c = :eventId
                WITH SECURITY_ENFORCED
            ];
            return eventAttendeesList;
            
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
}